index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

record-count:
    path: /api/record/count
    controller: App\Controller\RecordController::count

record:
    type:     rest
    resource: App\Controller\RecordController
    prefix:   /api

alcohol:
    type:     rest
    resource: App\Controller\AlcoholController
    prefix:   /api

feeding:
    type:     rest
    resource: App\Controller\FeedingController
    prefix:   /api

person:
    type:     rest
    resource: App\Controller\PersonController
    prefix:   /api
