index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

record-count:
    path: /record/count
    controller: App\Controller\RecordController::count
    prefix:   /healthcor/api

record-last:
    path: /record/last
    controller: App\Controller\RecordController::last
    prefix:   /healthcor/api

record:
    type:     rest
    resource: App\Controller\RecordController
    prefix:   /healthcor/api

alcohol:
    type:     rest
    resource: App\Controller\AlcoholController
    prefix:   /healthcor/api

feeding:
    type:     rest
    resource: App\Controller\FeedingController
    prefix:   /healthcor/api
