index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

record-count:
    path: /healthcor/api/record/count
    controller: App\Controller\RecordController::count

record-last:
    path: /healthcor/api/record/last
    controller: App\Controller\RecordController::last

record:
    type:     rest
    resource: App\Controller\RecordController
    prefix:   /healthcor/api

logout:
    path: /logout
